/**
 * The share card generated by `app/opengraph-image.tsx` / `app/twitter-image.tsx`.
 *
 * Metadata merges shallowly: a page that declares its own `openGraph` or
 * `twitter` replaces the root layout's wholesale, and the file-based card goes
 * with it. Every such page spreads these back in so it keeps a preview image.
 * Size and alt mirror the exports in `app/opengraph-image.tsx`.
 */
const card = {
  width: 1200,
  height: 630,
  alt: 'AIC — AI Systems, Business Automation & Web Applications',
}

export const openGraphImages = { images: [{ url: '/opengraph-image', ...card }] }

export const twitterImages = { images: [{ url: '/twitter-image', ...card }] }
